name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build, tag, and push image for docker hub
      run: |
        cd test1
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
 
    - name: checkout 
      uses: actions/checkout@v2   
      
    - name: Repository Dispatch to Devops
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.NODE_ACCESS }} 
        repository: kamalkishorsingh/node  
        event-type: version-update
        client-payload: '{"branch": "${{ github.ref_name }}", "sha": "${{ github.sha }}"}'
        


