name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build, tag, and push image for docker hub
      run: |
        newtag=$(jq -r '.version' /test1/package.json)
        echo "$newtag"


