name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build, tag, and push image for docker hub
      run: |
        cd test1
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
        cd
        git clone -b master https://github.com/kamalkishorsingh/node.git
        cd node/test1
        cat values.yaml
        pwd
        oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}')
        echo "$oldimage"
        sed -i "s/$oldimage/$newtag/" ./values.yaml && cat values.yaml
        git config user.email "kamalkishorsingh3@gmail.com"
        git config user.name "kamalkishorsingh"
        pwd
        git add .
        git commit -m "Add node repo values.yaml file"
        cd ..
        cat .git/config
        git push origin master
      env:
        PAT_TOKEN: ${{ secrets.NODE_ACCESS }}

        


