name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build, tag, and push image for docker hub
      run: |
        cd test1
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
 
    - name: Test secret
     run: |
       echo
     env:
       Devops: ${{ secrets.NODE_ACCESS  }} 
       
    - uses: actions/checkout@v2    
      with:
        repository: kamalkishorsingh/node
        token: ${{ secrets.NODE_ACCESS }}
        


