name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - new-master
    paths:
      - 'test1/**'
env:
  APP_FOLDER: test1
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: step1 Build, tag, and push image for docker hub
      run: |
        pwd
        echo "folder"
        cd "$APP_FOLDER"
        pwd
        ls -al
        brancename=$(git branch)
        echo "$brancename"
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
        echo "build step"
  repoupdate:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v3
        with:
          repository: kamalkishorsingh/node
          ref: refs/heads/kktest
          HELM_REPO_UPDATE: ${{ secrets.HELM_REPO_UPDATE }}
      - name: Build, tag, and push image for docker hub
        run: |
          ls -al
          newtag=$(jq -r '.version' package.json)
          echo "$newtag"
          branchname=$(git branch)
          echo "$branchname"
          ls -al 
          pwd
          cd && cd /home/runner/work/test-build/test-build/
          oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}') && echo "Old Tag :$oldimage"
          cd /home/runner/work/test-build/test-build/ && sed -i "s/$oldimage/kk/" ./values.yaml && cat values.yaml
