name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: step1 Build, tag, and push image for docker hub
      run: |
        cd test1
        ls -al
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
        echo "build step"

  repoupdate:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Step2 Build, tag, and push image for docker hub
      run: |
        cd test1
        newtag=$(jq -r '.version' package.json) 
        echo "$newtag"
        cd
        git clone -b master https://github.com/kamalkishorsingh/node.git && cd node/test1 && git checkout main && pwd
        oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}')
        echo "$oldimage"
        sed -i "s/$oldimage/$newtag/" ./values.yaml && cat values.yaml
        git config user.email "kamalkishorsingh3@gmail.com" && git config user.name "kamalkishorsingh"
        pwd
        cd /home/runner/node
        git add .
        git commit -m "Add test1 values.yaml file updated date:- $(date +'%Y-%m-%d %H:%M:%S')"
        git push https://$HELM_REPO_UPDATE:x-oauth-basic@github.com/kamalkishorsingh/node.git HEAD:main
      env:
        HELM_REPO_UPDATE: ${{ secrets.HELM_REPO_UPDATE }}

        


