name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build, tag, and push image for docker hub
      run: |
        cd test1
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
 
    - name: Clone private repo and push changes
      uses: actions/checkout@v2
      with:
        repository: kamalkishorsingh/node
        token: ${{ secrets.NODE_ACCESS }}
        ref: master
      run: |
        git config user.name "kamalkishorsingh"
        git config user.email "kamalkishorsingh3@gmail.com"
        oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}')
        sed -i "s/$oldimage/$newtag/" ./values.yaml
        git add .
        git commit -m "Update file"
        git push
        


