name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - name: Set Variable 1
      run: echo "MY_VAR_1=hello world" >> $GITHUB_ENV
    - name: Set Variable 2
      run: echo "MY_VAR_2=new value" >> $GITHUB_ENV
    - name: Use Variables
      run: |
        echo "The value of MY_VAR_1 is $MY_VAR_1"
        echo "The value of MY_VAR_2 is $MY_VAR_2"
        


