name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'
env: 
  oldimage: "cd test1 && oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}')"
  newtag: "cd test1 && newtag=$(jq -r '.version' package.json)"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: echo $oldimage
      - run: echo "$newtag"
