name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build, tag, and push image for docker hub
      run: |
        cd test1
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"

    - name: Clone Private Repo
      run: |
        git clone -b master https://github.com/kamalkishorsingh/node.git
        cd node/test1
        cat values.yaml
        git config user.email "kamalkishorsingh@gmail.com"
        git config user.name "kamalkishorsingh"
        cd
        cd test1
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
      env:
        PAT_TOKEN: ${{ secrets.NODE_ACCESS }}
    - name: Make Changes
      run: |
        cd node/test1/
        oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}')
        echo "$oldimage"
      env:
        PAT_TOKEN: ${{ secrets.NODE_ACCESS }}
        


