
name: deploy-test1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd test1 && newtag=$(jq -r '.version' package.json) && echo "The version is $newtag"
      - run: cd test1 && oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}') && echo $oldimage
      
      - name: Replace string in file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: test1/values.yaml
          old-string: ${{ oldimage }}
          new-string: ${{ newtag }}
