name: deploy-sme-auth
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      env:
        COMMIT_VAR: ${{ contains(github.event.head_commit.message, '[commit var]') }}
      run:  
        - '${COMMIT_VAR}/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ${COMMIT_VAR} && bash ${COMMIT_VAR}.sh
