name: deploy-test2
on:
  push:
    branches:
      - new-master
    paths:
      - 'test2/**'
  workflow_run:
    workflows: ["Other Workflow"]
    types:
      - completed

env:
  APP_FOLDER: test2
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for Other Workflow
      run: |
        while [ "$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs \
                    | jq -r '.jobs[].status' | grep -vE 'completed|skipped|neutral' | wc -l)" -gt 0 ]; do
            sleep 120
        done
          
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: step1 Build, tag, and push image for docker hub
      run: |
        pwd
        echo "folder"
        cd "$APP_FOLDER"
        pwd
        ls -al
        brancename=$(git branch)
        echo "$brancename"
        newtag=$(jq -r '.version' package.json)
        echo "$newtag"
        echo "build step"

  repoupdate:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Step2 Build, tag, and push image for docker hub
      run: |
        cd "$APP_FOLDER"
        newtag=$(jq -r '.version' package.json) && echo "New Tag : $newtag"
        cd
        git clone -b master https://github.com/kamalkishorsingh/node.git && cd node/"$APP_FOLDER" && git checkout kktest
        oldimage=$(cat values.yaml | grep image_tag | awk '{print$2}') && echo "Old Tag :$oldimage"
        sed -i "s/$oldimage/$newtag/" ./values.yaml && cat values.yaml
        git config user.email "kamalkishorsingh3@gmail.com" && git config user.name "kamalkishorsingh"
        git add .
        git commit -m "Add '$APP_FOLDER' values.yaml file updated date:- $(date +'%Y-%m-%d %H:%M:%S')"
        git push https://$HELM_REPO_UPDATE:x-oauth-basic@github.com/kamalkishorsingh/node.git HEAD:kktest
      env:
        HELM_REPO_UPDATE: ${{ secrets.HELM_REPO_UPDATE }}
